CREATE TABLE "Clientes" (
    "IdCliente" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(255) NOT NULL,
    "Telefone" character varying(20) NOT NULL,
    "Email" character varying(255),
    "SenhaHash" character varying(255),
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("IdCliente")
);


CREATE TABLE "Empresas" (
    "IdEmpresa" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeFantasia" character varying(255) NOT NULL,
    "Cnpj" character varying(18) NOT NULL,
    "LogoUrl" character varying(255),
    CONSTRAINT "PK_Empresas" PRIMARY KEY ("IdEmpresa")
);


CREATE TABLE "Usuarios" (
    "IdUsuario" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "NmUsuario" text NOT NULL,
    "Email" text NOT NULL,
    "Senha" text NOT NULL,
    "Status" boolean NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("IdUsuario")
);


CREATE TABLE "Variacoes" (
    "IdVariacao" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "PrecoExtra" numeric(10,2),
    CONSTRAINT "PK_Variacoes" PRIMARY KEY ("IdVariacao")
);


CREATE TABLE "Lojas" (
    "IdLoja" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpresa" integer NOT NULL,
    "Endereco" character varying(255) NOT NULL,
    "Telefone" character varying(20),
    "Status" character varying(20) NOT NULL,
    "ConfigDelivery" jsonb,
    CONSTRAINT "PK_Lojas" PRIMARY KEY ("IdLoja"),
    CONSTRAINT "FK_Lojas_Empresas_IdEmpresa" FOREIGN KEY ("IdEmpresa") REFERENCES "Empresas" ("IdEmpresa") ON DELETE RESTRICT
);


CREATE TABLE "Adicionais" (
    "IdAdicional" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Preco" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_Adicionais" PRIMARY KEY ("IdAdicional"),
    CONSTRAINT "FK_Adicionais_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT
);


CREATE TABLE "Bairros" (
    "IdBairro" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "TaxaEntrega" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_Bairros" PRIMARY KEY ("IdBairro"),
    CONSTRAINT "FK_Bairros_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT
);


CREATE TABLE "CaixaFechamentos" (
    "IdFechamento" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "IdUsuario" integer NOT NULL,
    "SaldoInicial" numeric(10,2) NOT NULL,
    "SaldoFinal" numeric(10,2) NOT NULL,
    "Inicio" timestamp with time zone NOT NULL,
    "Fim" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CaixaFechamentos" PRIMARY KEY ("IdFechamento"),
    CONSTRAINT "FK_CaixaFechamentos_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT,
    CONSTRAINT "FK_CaixaFechamentos_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("IdUsuario") ON DELETE RESTRICT
);


CREATE TABLE "CaixaMovimentos" (
    "IdMovimento" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "IdUsuario" integer NOT NULL,
    "Tipo" character varying(20) NOT NULL,
    "Valor" numeric(10,2) NOT NULL,
    "Descricao" character varying(255),
    "CriadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CaixaMovimentos" PRIMARY KEY ("IdMovimento"),
    CONSTRAINT "FK_CaixaMovimentos_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT,
    CONSTRAINT "FK_CaixaMovimentos_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("IdUsuario") ON DELETE RESTRICT
);


CREATE TABLE "Categorias" (
    "IdCategoria" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Ordem" integer NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("IdCategoria"),
    CONSTRAINT "FK_Categorias_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT
);


CREATE TABLE "Enderecos" (
    "IdEndereco" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCliente" bigint NOT NULL,
    "IdBairro" integer NOT NULL,
    "Logradouro" character varying(255) NOT NULL,
    "Numero" character varying(20) NOT NULL,
    "Complemento" character varying(100),
    "Cep" character varying(10),
    "Cidade" character varying(100) NOT NULL,
    "Principal" boolean NOT NULL,
    CONSTRAINT "PK_Enderecos" PRIMARY KEY ("IdEndereco"),
    CONSTRAINT "FK_Enderecos_Bairros_IdBairro" FOREIGN KEY ("IdBairro") REFERENCES "Bairros" ("IdBairro") ON DELETE RESTRICT,
    CONSTRAINT "FK_Enderecos_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clientes" ("IdCliente") ON DELETE RESTRICT
);


CREATE TABLE "Produtos" (
    "IdProduto" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCategoria" integer NOT NULL,
    "IdLoja" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Descricao" character varying(500),
    "PrecoBase" numeric(10,2) NOT NULL,
    "Ativo" boolean NOT NULL,
    "TempoPreparoMin" integer,
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("IdProduto"),
    CONSTRAINT "FK_Produtos_Categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES "Categorias" ("IdCategoria") ON DELETE RESTRICT,
    CONSTRAINT "FK_Produtos_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT
);


CREATE TABLE "Pedidos" (
    "IdPedido" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdLoja" integer NOT NULL,
    "IdCliente" bigint NOT NULL,
    "IdEndereco" bigint NOT NULL,
    "IdEntregador" integer,
    "Origem" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "FormaPagamento" character varying(50) NOT NULL,
    "PagamentoStatus" character varying(50) NOT NULL,
    "Subtotal" numeric(10,2) NOT NULL,
    "TaxaEntrega" numeric(10,2) NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL,
    "AtualizadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("IdPedido"),
    CONSTRAINT "FK_Pedidos_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES "Clientes" ("IdCliente") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pedidos_Enderecos_IdEndereco" FOREIGN KEY ("IdEndereco") REFERENCES "Enderecos" ("IdEndereco") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pedidos_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pedidos_Usuarios_IdEntregador" FOREIGN KEY ("IdEntregador") REFERENCES "Usuarios" ("IdUsuario") ON DELETE RESTRICT
);


CREATE TABLE "ProdutoVariacoes" (
    "IdProduto" bigint NOT NULL,
    "IdVariacao" integer NOT NULL,
    CONSTRAINT "PK_ProdutoVariacoes" PRIMARY KEY ("IdProduto", "IdVariacao"),
    CONSTRAINT "FK_ProdutoVariacoes_Produtos_IdProduto" FOREIGN KEY ("IdProduto") REFERENCES "Produtos" ("IdProduto") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProdutoVariacoes_Variacoes_IdVariacao" FOREIGN KEY ("IdVariacao") REFERENCES "Variacoes" ("IdVariacao") ON DELETE RESTRICT
);


CREATE TABLE "Avaliacoes" (
    "IdAvaliacao" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdPedido" bigint NOT NULL,
    "NotaPedido" integer NOT NULL,
    "NotaPlataforma" integer NOT NULL,
    "Comentario" character varying(500),
    "CriadoEm" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Avaliacoes" PRIMARY KEY ("IdAvaliacao"),
    CONSTRAINT "FK_Avaliacoes_Pedidos_IdPedido" FOREIGN KEY ("IdPedido") REFERENCES "Pedidos" ("IdPedido") ON DELETE RESTRICT
);


CREATE TABLE "KdsLogs" (
    "IdLog" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdPedido" bigint NOT NULL,
    "IdItem" bigint,
    "StatusAntigo" character varying(50),
    "StatusNovo" character varying(50),
    "IdUsuario" integer,
    "Origem" character varying(50),
    "Observacao" character varying(255),
    "RegistradoEm" timestamp with time zone,
    CONSTRAINT "PK_KdsLogs" PRIMARY KEY ("IdLog"),
    CONSTRAINT "FK_KdsLogs_Pedidos_IdPedido" FOREIGN KEY ("IdPedido") REFERENCES "Pedidos" ("IdPedido") ON DELETE RESTRICT,
    CONSTRAINT "FK_KdsLogs_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("IdUsuario") ON DELETE RESTRICT
);


CREATE TABLE "KdsPedidos" (
    "IdKdsPedido" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdPedido" bigint NOT NULL,
    "IdLoja" integer NOT NULL,
    "StatusCozinha" character varying(50),
    "Prioridade" integer,
    "TempoEstimadoPreparo" integer,
    "TempoRealPreparo" integer,
    "CriadoEm" timestamp with time zone,
    "IniciadoEm" timestamp with time zone,
    "FinalizadoEm" timestamp with time zone,
    CONSTRAINT "PK_KdsPedidos" PRIMARY KEY ("IdKdsPedido"),
    CONSTRAINT "FK_KdsPedidos_Lojas_IdLoja" FOREIGN KEY ("IdLoja") REFERENCES "Lojas" ("IdLoja") ON DELETE RESTRICT,
    CONSTRAINT "FK_KdsPedidos_Pedidos_IdPedido" FOREIGN KEY ("IdPedido") REFERENCES "Pedidos" ("IdPedido") ON DELETE RESTRICT
);


CREATE TABLE "PedidoItens" (
    "IdPedidoItem" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdPedido" bigint NOT NULL,
    "IdProduto" bigint NOT NULL,
    "IdVariacao" integer,
    "Quantidade" integer NOT NULL,
    "ValorUnitario" numeric(10,2) NOT NULL,
    "Observacao" character varying(255),
    CONSTRAINT "PK_PedidoItens" PRIMARY KEY ("IdPedidoItem"),
    CONSTRAINT "FK_PedidoItens_Pedidos_IdPedido" FOREIGN KEY ("IdPedido") REFERENCES "Pedidos" ("IdPedido") ON DELETE RESTRICT,
    CONSTRAINT "FK_PedidoItens_Produtos_IdProduto" FOREIGN KEY ("IdProduto") REFERENCES "Produtos" ("IdProduto") ON DELETE RESTRICT,
    CONSTRAINT "FK_PedidoItens_Variacoes_IdVariacao" FOREIGN KEY ("IdVariacao") REFERENCES "Variacoes" ("IdVariacao") ON DELETE RESTRICT
);


CREATE TABLE "KdsPedidoItens" (
    "IdKdsItem" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdKdsPedido" bigint NOT NULL,
    "IdProduto" bigint NOT NULL,
    "NomeProduto" character varying(255),
    "Variacao" character varying(100),
    "Quantidade" integer,
    "Observacao" character varying(255),
    "StatusItem" character varying(50),
    CONSTRAINT "PK_KdsPedidoItens" PRIMARY KEY ("IdKdsItem"),
    CONSTRAINT "FK_KdsPedidoItens_KdsPedidos_IdKdsPedido" FOREIGN KEY ("IdKdsPedido") REFERENCES "KdsPedidos" ("IdKdsPedido") ON DELETE RESTRICT,
    CONSTRAINT "FK_KdsPedidoItens_Produtos_IdProduto" FOREIGN KEY ("IdProduto") REFERENCES "Produtos" ("IdProduto") ON DELETE RESTRICT
);


CREATE TABLE "PedidoItemAdicionais" (
    "IdPedidoItem" bigint NOT NULL,
    "IdAdicional" integer NOT NULL,
    "Preco" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PedidoItemAdicionais" PRIMARY KEY ("IdPedidoItem", "IdAdicional"),
    CONSTRAINT "FK_PedidoItemAdicionais_Adicionais_IdAdicional" FOREIGN KEY ("IdAdicional") REFERENCES "Adicionais" ("IdAdicional") ON DELETE RESTRICT,
    CONSTRAINT "FK_PedidoItemAdicionais_PedidoItens_IdPedidoItem" FOREIGN KEY ("IdPedidoItem") REFERENCES "PedidoItens" ("IdPedidoItem") ON DELETE RESTRICT
);


CREATE TABLE "Perfis" (
    "IdPerfil" integer GENERATED BY DEFAULT AS IDENTITY,
    "NmPerfil" text NOT NULL,
    "Descricao" text NOT NULL,
    "UsuarioPerfilIdUsuarioPerfil" integer NOT NULL,
    CONSTRAINT "PK_Perfis" PRIMARY KEY ("IdPerfil")
);


CREATE TABLE "UsuariosPerfis" (
    "IdUsuarioPerfil" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdUsuario" integer NOT NULL,
    "IdPerfil" integer NOT NULL,
    CONSTRAINT "PK_UsuariosPerfis" PRIMARY KEY ("IdUsuarioPerfil"),
    CONSTRAINT "FK_UsuariosPerfis_Perfis_IdPerfil" FOREIGN KEY ("IdPerfil") REFERENCES "Perfis" ("IdPerfil") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuariosPerfis_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("IdUsuario") ON DELETE CASCADE
);


CREATE INDEX "IX_Adicionais_IdLoja" ON "Adicionais" ("IdLoja");


CREATE UNIQUE INDEX "IX_Avaliacoes_IdPedido" ON "Avaliacoes" ("IdPedido");


CREATE INDEX "IX_Bairros_IdLoja" ON "Bairros" ("IdLoja");


CREATE INDEX "IX_CaixaFechamentos_IdLoja" ON "CaixaFechamentos" ("IdLoja");


CREATE INDEX "IX_CaixaFechamentos_IdUsuario" ON "CaixaFechamentos" ("IdUsuario");


CREATE INDEX "IX_CaixaMovimentos_IdLoja" ON "CaixaMovimentos" ("IdLoja");


CREATE INDEX "IX_CaixaMovimentos_IdUsuario" ON "CaixaMovimentos" ("IdUsuario");


CREATE INDEX "IX_Categorias_IdLoja" ON "Categorias" ("IdLoja");


CREATE UNIQUE INDEX "IX_Clientes_Email" ON "Clientes" ("Email") WHERE "Email" IS NOT NULL;


CREATE UNIQUE INDEX "IX_Empresas_Cnpj" ON "Empresas" ("Cnpj");


CREATE INDEX "IX_Enderecos_IdBairro" ON "Enderecos" ("IdBairro");


CREATE INDEX "IX_Enderecos_IdCliente" ON "Enderecos" ("IdCliente");


CREATE INDEX "IX_KdsLogs_IdPedido" ON "KdsLogs" ("IdPedido");


CREATE INDEX "IX_KdsLogs_IdUsuario" ON "KdsLogs" ("IdUsuario");


CREATE INDEX "IX_KdsPedidoItens_IdKdsPedido" ON "KdsPedidoItens" ("IdKdsPedido");


CREATE INDEX "IX_KdsPedidoItens_IdProduto" ON "KdsPedidoItens" ("IdProduto");


CREATE INDEX "IX_KdsPedidos_IdLoja" ON "KdsPedidos" ("IdLoja");


CREATE INDEX "IX_KdsPedidos_IdPedido" ON "KdsPedidos" ("IdPedido");


CREATE INDEX "IX_Lojas_IdEmpresa" ON "Lojas" ("IdEmpresa");


CREATE INDEX "IX_PedidoItemAdicionais_IdAdicional" ON "PedidoItemAdicionais" ("IdAdicional");


CREATE INDEX "IX_PedidoItens_IdPedido" ON "PedidoItens" ("IdPedido");


CREATE INDEX "IX_PedidoItens_IdProduto" ON "PedidoItens" ("IdProduto");


CREATE INDEX "IX_PedidoItens_IdVariacao" ON "PedidoItens" ("IdVariacao");


CREATE INDEX "IX_Pedidos_IdCliente" ON "Pedidos" ("IdCliente");


CREATE INDEX "IX_Pedidos_IdEndereco" ON "Pedidos" ("IdEndereco");


CREATE INDEX "IX_Pedidos_IdEntregador" ON "Pedidos" ("IdEntregador");


CREATE INDEX "IX_Pedidos_IdLoja" ON "Pedidos" ("IdLoja");


CREATE INDEX "IX_Perfis_UsuarioPerfilIdUsuarioPerfil" ON "Perfis" ("UsuarioPerfilIdUsuarioPerfil");


CREATE INDEX "IX_Produtos_IdCategoria" ON "Produtos" ("IdCategoria");


CREATE INDEX "IX_Produtos_IdLoja" ON "Produtos" ("IdLoja");


CREATE INDEX "IX_ProdutoVariacoes_IdVariacao" ON "ProdutoVariacoes" ("IdVariacao");


CREATE INDEX "IX_UsuariosPerfis_IdPerfil" ON "UsuariosPerfis" ("IdPerfil");


CREATE UNIQUE INDEX "IX_UsuariosPerfis_IdUsuario" ON "UsuariosPerfis" ("IdUsuario");


ALTER TABLE "Perfis" ADD CONSTRAINT "FK_Perfis_UsuariosPerfis_UsuarioPerfilIdUsuarioPerfil" FOREIGN KEY ("UsuarioPerfilIdUsuarioPerfil") REFERENCES "UsuariosPerfis" ("IdUsuarioPerfil") ON DELETE CASCADE;


