// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PedidoMestre.Data;

#nullable disable

namespace PedidoMestre.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125232405_AdicionarTaxaPorKmEmpresaERelacionamentoUsuarioLoja")]
    partial class AdicionarTaxaPorKmEmpresaERelacionamentoUsuarioLoja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PedidoMestre.Models.Avaliacoes.Avaliacao", b =>
                {
                    b.Property<long>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAvaliacao"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<int>("NotaPedido")
                        .HasColumnType("integer");

                    b.Property<int>("NotaPlataforma")
                        .HasColumnType("integer");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Caixa.CaixaFechamento", b =>
                {
                    b.Property<int>("IdFechamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFechamento"));

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdFechamento");

                    b.HasIndex("IdLoja");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CaixaFechamentos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Caixa.CaixaMovimento", b =>
                {
                    b.Property<long>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMovimento"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdLoja");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CaixaMovimentos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Clientes.Cliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdCliente");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Clientes.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdBairro")
                        .HasColumnType("integer");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdBairro");

                    b.HasIndex("IdCliente");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Empresas.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TaxaPorKm")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("PedidoMestre.Models.Empresas.Loja", b =>
                {
                    b.Property<int>("IdLoja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLoja"));

                    b.Property<string>("ConfigDelivery")
                        .HasColumnType("jsonb");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HorarioAbertura")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HorarioFechamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<decimal?>("RaioEntrega")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdLoja");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("PedidoMestre.Models.Geral.Bairro", b =>
                {
                    b.Property<int>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBairro"));

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TaxaEntrega")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdBairro");

                    b.HasIndex("IdLoja");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsLog", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLog"));

                    b.Property<long?>("IdItem")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Origem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusAntigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusNovo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("KdsLogs");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsPedido", b =>
                {
                    b.Property<long>("IdKdsPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdKdsPedido"));

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<string>("StatusCozinha")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TempoEstimadoPreparo")
                        .HasColumnType("integer");

                    b.Property<int?>("TempoRealPreparo")
                        .HasColumnType("integer");

                    b.HasKey("IdKdsPedido");

                    b.HasIndex("IdLoja");

                    b.HasIndex("IdPedido");

                    b.ToTable("KdsPedidos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsPedidoItem", b =>
                {
                    b.Property<long>("IdKdsItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdKdsItem"));

                    b.Property<long>("IdKdsPedido")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeProduto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("StatusItem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Variacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdKdsItem");

                    b.HasIndex("IdKdsPedido");

                    b.HasIndex("IdProduto");

                    b.ToTable("KdsPedidoItens");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.Pedido", b =>
                {
                    b.Property<long>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPedido"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEndereco")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdEntregador")
                        .HasColumnType("integer");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PagamentoStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TaxaEntrega")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdEntregador");

                    b.HasIndex("IdLoja");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.PedidoItem", b =>
                {
                    b.Property<long>("IdPedidoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPedidoItem"));

                    b.Property<long>("IdPedido")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdVariacao")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedidoItem");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdVariacao");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.PedidoItemAdicional", b =>
                {
                    b.Property<long>("IdPedidoItem")
                        .HasColumnType("bigint");

                    b.Property<int>("IdAdicional")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedidoItem", "IdAdicional");

                    b.HasIndex("IdAdicional");

                    b.ToTable("PedidoItemAdicionais");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Adicional", b =>
                {
                    b.Property<int>("IdAdicional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAdicional"));

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdAdicional");

                    b.HasIndex("IdLoja");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdLoja");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProduto"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TempoPreparoMin")
                        .HasColumnType("integer");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdLoja");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.ProdutoVariacao", b =>
                {
                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint");

                    b.Property<int>("IdVariacao")
                        .HasColumnType("integer");

                    b.HasKey("IdProduto", "IdVariacao");

                    b.HasIndex("IdVariacao");

                    b.ToTable("ProdutoVariacoes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Variacao", b =>
                {
                    b.Property<int>("IdVariacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVariacao"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PrecoExtra")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdVariacao");

                    b.ToTable("Variacoes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NmPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioPerfilIdUsuarioPerfil")
                        .HasColumnType("integer");

                    b.HasKey("IdPerfil");

                    b.HasIndex("UsuarioPerfilIdUsuarioPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdLoja")
                        .HasColumnType("integer");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdLoja");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.UsuarioPerfil", b =>
                {
                    b.Property<int>("IdUsuarioPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuarioPerfil"));

                    b.Property<int>("IdPerfil")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuarioPerfil");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("UsuariosPerfis");
                });

            modelBuilder.Entity("PedidoMestre.Models.Avaliacoes.Avaliacao", b =>
                {
                    b.HasOne("PedidoMestre.Models.Pedidos.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PedidoMestre.Models.Caixa.CaixaFechamento", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PedidoMestre.Models.Caixa.CaixaMovimento", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PedidoMestre.Models.Clientes.Endereco", b =>
                {
                    b.HasOne("PedidoMestre.Models.Geral.Bairro", "Bairro")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Clientes.Cliente", "Cliente")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PedidoMestre.Models.Empresas.Loja", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Empresa", "Empresa")
                        .WithMany("Lojas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PedidoMestre.Models.Geral.Bairro", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany("Bairros")
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsLog", b =>
                {
                    b.HasOne("PedidoMestre.Models.Pedidos.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsPedido", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Pedidos.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsPedidoItem", b =>
                {
                    b.HasOne("PedidoMestre.Models.Pedidos.KdsPedido", "KdsPedido")
                        .WithMany("Itens")
                        .HasForeignKey("IdKdsPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KdsPedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.Pedido", b =>
                {
                    b.HasOne("PedidoMestre.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Clientes.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Usuarios.Usuario", "Entregador")
                        .WithMany()
                        .HasForeignKey("IdEntregador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");

                    b.Navigation("Entregador");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.PedidoItem", b =>
                {
                    b.HasOne("PedidoMestre.Models.Pedidos.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Produtos.Variacao", "Variacao")
                        .WithMany()
                        .HasForeignKey("IdVariacao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("Variacao");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.PedidoItemAdicional", b =>
                {
                    b.HasOne("PedidoMestre.Models.Produtos.Adicional", "Adicional")
                        .WithMany()
                        .HasForeignKey("IdAdicional")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Pedidos.PedidoItem", "PedidoItem")
                        .WithMany("Adicionais")
                        .HasForeignKey("IdPedidoItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adicional");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Adicional", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Categoria", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Produto", b =>
                {
                    b.HasOne("PedidoMestre.Models.Produtos.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.ProdutoVariacao", b =>
                {
                    b.HasOne("PedidoMestre.Models.Produtos.Produto", "Produto")
                        .WithMany("ProdutoVariacoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Produtos.Variacao", "Variacao")
                        .WithMany("ProdutoVariacoes")
                        .HasForeignKey("IdVariacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Variacao");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.Perfil", b =>
                {
                    b.HasOne("PedidoMestre.Models.Usuarios.UsuarioPerfil", "UsuarioPerfil")
                        .WithMany()
                        .HasForeignKey("UsuarioPerfilIdUsuarioPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioPerfil");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.Usuario", b =>
                {
                    b.HasOne("PedidoMestre.Models.Empresas.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("IdLoja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.UsuarioPerfil", b =>
                {
                    b.HasOne("PedidoMestre.Models.Usuarios.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PedidoMestre.Models.Usuarios.Usuario", "Usuario")
                        .WithOne("UsuarioPerfil")
                        .HasForeignKey("PedidoMestre.Models.Usuarios.UsuarioPerfil", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PedidoMestre.Models.Clientes.Cliente", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Empresas.Empresa", b =>
                {
                    b.Navigation("Lojas");
                });

            modelBuilder.Entity("PedidoMestre.Models.Empresas.Loja", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("PedidoMestre.Models.Geral.Bairro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.KdsPedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PedidoMestre.Models.Pedidos.PedidoItem", b =>
                {
                    b.Navigation("Adicionais");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Produto", b =>
                {
                    b.Navigation("ProdutoVariacoes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Produtos.Variacao", b =>
                {
                    b.Navigation("ProdutoVariacoes");
                });

            modelBuilder.Entity("PedidoMestre.Models.Usuarios.Usuario", b =>
                {
                    b.Navigation("UsuarioPerfil")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
